-- Table: public.Summary

-- DROP TABLE public."Summary";

CREATE TABLE public."Summary"
(
    "Id" uuid NOT NULL,
    "JEPostingDesignation" character varying(50) COLLATE pg_catalog."default",
    "DateCreated" date,
    "JECreationSource" character varying(50) COLLATE pg_catalog."default",
    "Name" character varying(350) COLLATE pg_catalog."default",
    "ScheduledRecurring" character varying(3) COLLATE pg_catalog."default" NOT NULL,
    "IsApproverCustomized" character varying(3) COLLATE pg_catalog."default",
    "IsPostedSuccessfullyToERP" character varying(3) COLLATE pg_catalog."default",
    "PostingDescription" character varying(350) COLLATE pg_catalog."default",
    "PostingMethod" character varying(20) COLLATE pg_catalog."default",
    "PostingDestination" character varying(350) COLLATE pg_catalog."default",
    "BypassPosting" character varying(3) COLLATE pg_catalog."default",
    "PeriodDisplay" character varying(350) COLLATE pg_catalog."default",
    "Period" integer,
    "JE_Period_Year" integer,
    "TemplateDescription" character varying(500) COLLATE pg_catalog."default",
    "TemplateName" character varying(350) COLLATE pg_catalog."default",
    "TemplateActive" character varying(3) COLLATE pg_catalog."default",
    "ApproverIsOptional" character varying(3) COLLATE pg_catalog."default",
    "TemplatePostingRule" character varying(350) COLLATE pg_catalog."default",
    "RequireFiles" character varying(3) COLLATE pg_catalog."default",
    "FileCount" integer,
    "PrepName" character varying(100) COLLATE pg_catalog."default",
    "PrepStatus" character varying(50) COLLATE pg_catalog."default",
    "App1Name" character varying(100) COLLATE pg_catalog."default",
    "App2Name" character varying(100) COLLATE pg_catalog."default",
    "App3Name" character varying(100) COLLATE pg_catalog."default",
    "App4Name" character varying(100) COLLATE pg_catalog."default",
    "App5Name" character varying(100) COLLATE pg_catalog."default",
    "App6Name" character varying(100) COLLATE pg_catalog."default",
    "App1Status" character varying(50) COLLATE pg_catalog."default",
    "App2Status" character varying(50) COLLATE pg_catalog."default",
    "App3Status" character varying(50) COLLATE pg_catalog."default",
    "App4Status" character varying(50) COLLATE pg_catalog."default",
    "App5Status" character varying(50) COLLATE pg_catalog."default",
    "App6Status" character varying(50) COLLATE pg_catalog."default",
    "CreatedByName" character varying(100) COLLATE pg_catalog."default",
    "JENotes" character varying COLLATE pg_catalog."default",
    "ANETLinkName" character varying(200) COLLATE pg_catalog."default",
    "ANETLinkNumber" character varying(550) COLLATE pg_catalog."default",
    "HasANETLink" character varying(3) COLLATE pg_catalog."default",
    "PostingHasErrors" character varying(3) COLLATE pg_catalog."default",
    "PostingComplete" character varying(3) COLLATE pg_catalog."default",
    "DocumentTotalCredit" numeric(36,2),
    "DocumentTotalDebit" numeric(36,2),
    "ConvertedTotal" character varying COLLATE pg_catalog."default",
    "ConvertedMaxAmount" numeric(21,2),
    "JE_Description" character varying(500) COLLATE pg_catalog."default",
    "JE_Document_Number" character varying(500) COLLATE pg_catalog."default",
    "JE_Entity" integer,
    "JE_TrintechObjKey" character varying(350) COLLATE pg_catalog."default",
    "JE_Offset_Account" character varying(350) COLLATE pg_catalog."default",
    "JE_Offset_Business_Area" character varying(50) COLLATE pg_catalog."default",
    "JE_Offset_Item_Text" character varying(350) COLLATE pg_catalog."default",
    "JE_Posted_By" character varying(50) COLLATE pg_catalog."default",
    "JE_Posting_Date" date,
    "JE_Recurring" character varying(3) COLLATE pg_catalog."default",
    "JE_Reversal_Date" date,
    "JE_SAPObjKey" character varying(350) COLLATE pg_catalog."default",
    "RiskRating" integer,
    "ApprovalStatus" character varying(4) COLLATE pg_catalog."default",
    "JENotesLink" character varying COLLATE pg_catalog."default",
    "PeriodFk" uuid,
    "RemoteTab" character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "Summary_pkey" PRIMARY KEY ("Id")
)

TABLESPACE pg_default;

ALTER TABLE public."Summary"
    OWNER to postgres;